export const agents = [
  {
    id: 'atlas',
    name: 'Agent Atlas',
    role: 'Routing Orchestrator',
    status: 'online',
    task: 'Balancing inference shards',
    latency: 42,
    queueDepth: 5,
    successRate: 98.9,
    load: 44,
    position: { x: 14, y: 24 },
    logs: ['Heartbeat stable', 'Rerouted APAC traffic', 'No failed handoffs in last hour'],
    latencyHistory: [37, 39, 41, 38, 42, 44, 40, 42],
    lastActivityOffsetMin: 1.2,
    lastHeartbeatOffsetSec: 42,
    heartbeatIntervalSec: 75,
    heartbeatPhase: 'sync',
  },
  {
    id: 'echo',
    name: 'Agent Echo',
    role: 'Comms QA Monitor',
    status: 'busy',
    task: 'Auditing escalation transcript',
    latency: 89,
    queueDepth: 11,
    successRate: 96.4,
    load: 78,
    position: { x: 33, y: 28 },
    logs: ['Flagged tone mismatch in incident #847', 'Queued compliance summary', 'Manual review in progress'],
    latencyHistory: [63, 70, 74, 79, 85, 88, 93, 89],
    lastActivityOffsetMin: 6.4,
    lastHeartbeatOffsetSec: 118,
    heartbeatIntervalSec: 90,
    heartbeatPhase: 'audit',
  },
  {
    id: 'forge',
    name: 'Agent Forge',
    role: 'Build & Infra',
    status: 'online',
    task: 'Canary deploy validation',
    latency: 53,
    queueDepth: 7,
    successRate: 97.3,
    load: 61,
    position: { x: 55, y: 22 },
    logs: ['Rebuilt worker image v2.14', 'Watching rollback guardrail', 'CPU saturation nominal'],
    latencyHistory: [47, 50, 52, 49, 54, 56, 58, 53],
    lastActivityOffsetMin: 3.1,
    lastHeartbeatOffsetSec: 56,
    heartbeatIntervalSec: 80,
    heartbeatPhase: 'deploy',
  },
  {
    id: 'nova',
    name: 'Agent Nova',
    role: 'Research Analyst',
    status: 'offline',
    task: 'Awaiting wake schedule',
    latency: 0,
    queueDepth: 0,
    successRate: 99.2,
    load: 0,
    position: { x: 76, y: 25 },
    logs: ['Last seen 11m ago', 'Nightly memory archive complete', 'No active assignments'],
    latencyHistory: [0, 0, 8, 0, 0, 0, 0, 0],
    lastActivityOffsetMin: 21.4,
    lastHeartbeatOffsetSec: 640,
    heartbeatIntervalSec: 120,
    heartbeatPhase: 'sleep',
  },
  {
    id: 'rift',
    name: 'Agent Rift',
    role: 'Threat Sentinel',
    status: 'error',
    task: 'Packet anomaly triage',
    latency: 221,
    queueDepth: 19,
    successRate: 88.7,
    load: 91,
    position: { x: 21, y: 64 },
    logs: ['Socket timeout on node 4', 'Retry budget exceeded', 'Escalation recommended'],
    latencyHistory: [132, 149, 161, 188, 210, 228, 217, 221],
    lastActivityOffsetMin: 11.2,
    lastHeartbeatOffsetSec: 248,
    heartbeatIntervalSec: 90,
    heartbeatPhase: 'triage',
  },
  {
    id: 'lumen',
    name: 'Agent Lumen',
    role: 'UX Simulation',
    status: 'busy',
    task: 'Running conversion heatmap',
    latency: 71,
    queueDepth: 9,
    successRate: 95.1,
    load: 73,
    position: { x: 39, y: 60 },
    logs: ['Generated 3 prototype variants', 'A/B sweep 62% complete', 'Insights queued for review'],
    latencyHistory: [54, 58, 64, 69, 73, 70, 75, 71],
    lastActivityOffsetMin: 4.6,
    lastHeartbeatOffsetSec: 88,
    heartbeatIntervalSec: 75,
    heartbeatPhase: 'analysis',
  },
  {
    id: 'quill',
    name: 'Agent Quill',
    role: 'Knowledge Scribe',
    status: 'online',
    task: 'Summarizing overnight changes',
    latency: 34,
    queueDepth: 3,
    successRate: 99.1,
    load: 31,
    position: { x: 58, y: 58 },
    logs: ['Generated executive digest', 'Tagged 14 policy updates', 'Awaiting publish approval'],
    latencyHistory: [28, 31, 33, 35, 32, 37, 34, 34],
    lastActivityOffsetMin: 2.2,
    lastHeartbeatOffsetSec: 35,
    heartbeatIntervalSec: 70,
    heartbeatPhase: 'scribe',
  },
  {
    id: 'warden',
    name: 'Agent Warden',
    role: 'Access Governor',
    status: 'busy',
    task: 'Rotating expiring keys',
    latency: 64,
    queueDepth: 8,
    successRate: 97.8,
    load: 66,
    position: { x: 79, y: 61 },
    logs: ['Revoked stale token set', 'MFA challenge refresh sent', 'Privilege drift scan running'],
    latencyHistory: [49, 55, 57, 62, 66, 69, 67, 64],
    lastActivityOffsetMin: 5.3,
    lastHeartbeatOffsetSec: 104,
    heartbeatIntervalSec: 80,
    heartbeatPhase: 'security',
  },
];

export const incidents = [
  { id: 'INC-847', severity: 'high', summary: 'Rift packet parser timeout cascade', owner: 'Agent Rift', timestamp: '07:14:02' },
  { id: 'INC-842', severity: 'medium', summary: 'Echo flagged escalation sentiment mismatch', owner: 'Agent Echo', timestamp: '07:11:44' },
  { id: 'INC-836', severity: 'low', summary: 'Forge canary metrics drift under load', owner: 'Agent Forge', timestamp: '07:09:18' },
];

export const jobQueue = [
  { id: 'JOB-9012', agent: 'Agent Atlas', type: 'Route rebalance', eta: '00:38', priority: 'high' },
  { id: 'JOB-9013', agent: 'Agent Lumen', type: 'UX cohort simulation', eta: '01:12', priority: 'medium' },
  { id: 'JOB-9014', agent: 'Agent Warden', type: 'Credential rotation', eta: '00:46', priority: 'high' },
  { id: 'JOB-9015', agent: 'Agent Quill', type: 'Knowledge digest publish', eta: '00:18', priority: 'low' },
];

export const alerts = [
  '07:14 UTC — Rift queue depth exceeded 18 tasks',
  '07:11 UTC — Forge canary checks 94% complete',
  '07:09 UTC — Atlas rerouted EU requests to backup fabric',
  '07:06 UTC — Warden completed key revocation sweep',
  '07:03 UTC — Echo opened manual QA review lane',
];

export const throughput = [54, 58, 63, 59, 66, 72, 68, 75, 79, 74, 82, 86, 80, 88, 92, 89];

export const timelineEvents = [
  { ts: '07:16:08', type: 'system', text: 'Dust suppression mesh calibrated in Sector B' },
  { ts: '07:14:02', type: 'incident', text: 'INC-847 raised by Rift (timeout cascade)' },
  { ts: '07:11:44', type: 'review', text: 'Echo opened manual compliance lane for escalation transcript' },
  { ts: '07:09:18', type: 'deploy', text: 'Forge canary drift detected under synthetic burst' },
  { ts: '07:06:55', type: 'security', text: 'Warden revoked stale token cluster set' },
  { ts: '07:03:09', type: 'routing', text: 'Atlas switched EU traffic to fallback fabric' },
];
